import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
<<<<<<< HEAD
import { Edu_NSW_ACT_Cursive } from "next/font/google";
import localfont from 'next/font/local';

import "./globals.css";
import localFont from "next/font/local";

=======
import "./globals.css";
import localFont from "next/font/local";


>>>>>>> master
const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

<<<<<<< HEAD
const edu = Edu_NSW_ACT_Cursive({
    variable: "--font-edu-cursive",
    subsets: ["latin"]
});

=======
>>>>>>> master
const modernNegraFont = localFont({
    variable: "--font-modernNegra",
    src: '../../public/fonts/modernNegraDemo.ttf',
    display: 'swap',
})

<<<<<<< HEAD
=======

>>>>>>> master
export const metadata: Metadata = {
    title: "Purple Pour",
    description: "Generated by create next app",
    icons: {
        icon: '/images/logo.png'
    }
<<<<<<< HEAD
};

=======

};
>>>>>>> master

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${modernNegraFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
