import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import localFont from "next/font/local";


const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const modernNegraFont = localFont({
    variable: "--font-modernNegra",
    src: '../../public/fonts/modernNegraDemo.ttf',
    display: 'swap',
})


export const metadata: Metadata = {
    title: "Purple Pour",
    description: "Generated by create next app",
    icons: {
        icon: '/images/logo.png'
    }

};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${modernNegraFont.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                {children}
            </body>
        </html>
    );
}
